src/main/resources/TypeScriptTypeGoat.ts
Notes:
- enums:
- removed:
- enums cannot be direct descendants of classes; enum declarations are statements and must appear in a block
- enums cannot accept decorators
- enums cannot have members
- classes
- removed:
- classes cannot be declared with a name as a direct child of a class; they can be declared as class attributes via assignment, as you have done, but there is no way to do this for abstract classes AFAIK (these are class expressions, not class declaration statements)
- functions
- changed:
- generic return types cannot use wildcard; variance is inferred
- removed:
- generics cannot use `super` in their constraints
=> Can't run tests yet due to a parsing failure.

js/src/runtime/PathPrefixes.ts, js/src/runtime/index.ts, js/src/runtime/vfs.ts, src/main/java/com/caoccao/javet/interop/JavetBridge.java, src/main/java/org/openrewrite/javascript/JavaScriptParser.java, src/main/java/org/openrewrite/javascript/internal/JavetUtils.java, src/main/java/org/openrewrite/javascript/internal/TypeScriptParserVisitor.java, src/main/java/org/openrewrite/javascript/internal/tsc/TSCConversions.java, src/main/java/org/openrewrite/javascript/internal/tsc/TSCGlobals.java, src/main/java/org/openrewrite/javascript/internal/tsc/TSCInstanceOfChecks.java, src/main/java/org/openrewrite/javascript/internal/tsc/TSCNodeList.java, src/main/java/org/openrewrite/javascript/internal/tsc/TSCObjectCache.java, src/main/java/org/openrewrite/javascript/internal/tsc/TSCProgramContext.java, src/main/java/org/openrewrite/javascript/internal/tsc/TSCRuntime.java, src/main/java/org/openrewrite/javascript/internal/tsc/TSCSourceFileContext.java, src/main/java/org/openrewrite/javascript/internal/tsc/TSCTypeChecker.java, src/main/java/org/openrewrite/javascript/internal/tsc/TSCV8Backed.java, src/main/java/org/openrewrite/javascript/internal/tsc/TSCV8Utils.java, src/main/java/org/openrewrite/javascript/internal/tsc/TSCV8ValueHolder.java, src/test/java/org/openrewrite/javascript/internal/V8InteropTests.java
- typescript wrapper JS
- make VFS tracing configurable
- V8 interop
- put lifecycle management into a base class for wrappers
- don't lazy-initialize wrappers within the program context
- don't use Java Map for passing named arguments to `makeFunction` (reference management behavior is unexpected)
- don't scatter `toClone()` around
- don't use default Javet `close()` utility
- prefix both lib and application paths
- fix bug with node list conversion
- parser
- fix extension bug
=> misc cleanup

gradle.properties, settings.gradle.kts
We fixed a couple of issues that should allow caching to be re-enabled:
1. LSTs would not deserialze. Fixed by removing `lombok.anyConstructor.addConstructorProperties=true` from lombok.config.
2. The wrong snapshots were loaded via `latest.integration`. Released `0.3.0`.
fixes #41
=> Re-enabled gradle build cache.

src/main/java/org/openrewrite/javascript/internal/TSCMapper.java, src/test/java/org/openrewrite/javascript/tree/ParserTest.java
The TSCMapper uses a map to collect the ParserInputs, which randomizes the order and causes multiple problems.
Ideally, we'll use the input list and parse the files, but there isn't time to refactor the TSCMapper.
For now, I added a `LinkedHashMap` to return the JS.CUs in the same order as the source files.
fixes #57
=> Preserve order of inputs in TSCMapper.

src/main/java/org/openrewrite/javascript/JavaScriptParser.java, src/main/java/org/openrewrite/javascript/internal/TSCMapper.java
TSCMapper will create ParserErrors when there is an exception that cannot be converted to a J.Unknown.
=> Revised TSCMapper to create ParseErrors.

src/main/java/org/openrewrite/javascript/JavaScriptParser.java
Exclude Yarn Plug'n'Play files from parsing (https://yarnpkg.com/features/pnp)
Reduce the parsing time of large projects
=> Exclude Yarn Plug'n'Play files

js/tsconfig.json, src/main/java/org/openrewrite/javascript/JavaScriptParser.java, src/main/java/org/openrewrite/javascript/internal/TypeScriptParserVisitor.java, src/test/java/org/openrewrite/javascript/tree/MethodInvocationTest.java
Changes:
- JavaScriptParser creates test files with `.ts` extension instead of `.js`
- Updated `ts.config` to match the script target in the runtime `index.ts` in`createScanner()`
- Updated tests to fail when ParserErrors are detected in the source.
fixes #56
=> Minor update to JavaScriptParser to generate correct AST elements.

src/main/java/org/openrewrite/javascript/internal/TypeScriptParserVisitor.java, src/main/java/org/openrewrite/javascript/internal/tsc/TSCRuntime.java, src/test/java/org/openrewrite/javascript/tree/CommentTest.java, src/test/java/org/openrewrite/javascript/tree/ParserPerfTest.java
Changes:
- Source text used to generate the `sourceFileContext` includes leading comments.
- Added `sourceStartsWithAtCursor` and updated methods that check if the source starts with text at the cursor to use `sourceStartsWithAtCursor`.
Notes:
Previously, the `sourceFileContext` did not include leading comments because `sourceFileV8.invokeString("getText")` does not include the leading comments. The `text` property consists of the leading comments, allowing the scanner to detect the `Trivial` tokens.
fixes #4
=> Preserve leading comments.

src/main/java/org/openrewrite/javascript/TypeScriptSignatureBuilder.java, src/main/java/org/openrewrite/javascript/TypeScriptTypeMapping.java, src/main/java/org/openrewrite/javascript/internal/TypeScriptParserVisitor.java
Changes:
- `hasProperty` is only used when the node isn't necessary.
- Replaced uses of `hasProperty` with optional properties with null checks.
=> Removed unnecessary calls to v8.

src/main/java/org/openrewrite/javascript/JavaScriptVisitor.java, src/main/java/org/openrewrite/javascript/internal/JavaScriptPrinter.java, src/main/java/org/openrewrite/javascript/internal/TypeScriptParserVisitor.java, src/main/java/org/openrewrite/javascript/tree/JS.java, src/main/java/org/openrewrite/javascript/tree/JsLeftPadded.java, src/test/java/org/openrewrite/javascript/tree/BinaryTest.java, src/test/java/org/openrewrite/javascript/tree/TypeOperatorTest.java
Add `JS.Binary` to support TS/JS specific binary type like `in`
=> Add JS.Binary to support TS/JS specific binary type like `in`

src/main/java/org/openrewrite/javascript/internal/JavaScriptPrinter.java, src/main/java/org/openrewrite/javascript/internal/TypeScriptParserVisitor.java, src/main/java/org/openrewrite/javascript/tree/JS.java, src/test/java/org/openrewrite/javascript/tree/UnaryTest.java
fixes https://github.com/openrewrite/rewrite-javascript/issues/90
currently, we have a model `TypeOperator` for type-operator, but I think it may be better to use a `Unary` to present type-operator since it's more generic.
=> Support `keyof` keyword

openrewrite/README.md, openrewrite/jest.config.js, openrewrite/package-lock.json, openrewrite/package.json, openrewrite/test/javascript/testHarness.ts, openrewrite/tsconfig.json
=> Fix modules resolution

build.gradle.kts, src/main/java/org/openrewrite/javascript/JavaScriptParser.java, src/main/resources/META-INF/package.json, src/test/java/org/openrewrite/javascript/JavaScriptParserTest.java
=> Add rewrite-remote installation support

build.gradle.kts, src/main/java/org/openrewrite/javascript/JavaScriptParser.java
=> add file-source handler

openrewrite/src/javascript/parser.ts
A `J.Unknown` inside a `JRightPadded` doesn't need any `Semicolon`, as the `J.Unknown` will already contain the semicolon in its source.
Also, the parser should not produce any unnecessary `JS.ExpressionStatement`s, as visitors like the visitor implementation in Java will automatically remove that and thus cause the tree to change.
=> No `Semicolon` for `J.Unknown` and no unnecessary `JS.ExpressionStatement`

openrewrite/src/javascript/parser.ts, openrewrite/test/javascript/parser/qualifiedName.test.ts, openrewrite/test/javascript/testHarness.ts
Most of the tests are skipped because enum, class, namespace constructions not supported yet.
Also modified testHarness runner to be able to join to remotely running rewrite-remote test engine
=> Implemented qualifiedName visitor

openrewrite/src/javascript/parser.ts, openrewrite/test/javascript/parser/class.test.ts, openrewrite/test/javascript/parser/variableDeclarations.test.ts, rewrite-javascript/src/main/java/org/openrewrite/javascript/internal/JavaScriptPrinter.java
The `visitClassDeclaration` method has been rewritten to be able to parse classes with several declared properties correctly.
Example:
```
class X {
a: number = 6;
b: string = "abc";
c /*asdasd*/ =  /*abc*/   5
}
```
=> Reworked classDeclaration visitor

openrewrite/src/javascript/parser.ts, openrewrite/test/javascript/parser/enum.test.ts, openrewrite/test/javascript/parser/qualifiedName.test.ts, rewrite-javascript/src/main/java/org/openrewrite/javascript/internal/JavaScriptPrinter.java
Implemented `visitEnumDeclaration` parser.
To implement Enum members' initialisation, had to override the `visitEnumValue` method at `JavaScriptPrinter` class.
=> Implemented Enum declaration support

openrewrite/src/java/remote/index.ts, openrewrite/src/java/remote/register.ts, openrewrite/src/javascript/remote/index.ts, openrewrite/src/javascript/remote/register.ts, openrewrite/src/yaml/remote/index.ts, openrewrite/src/yaml/remote/register.ts
- introduce codec registration functions
- moves away from registration being side effects but rather direct calls
- explicitly pass contexts
- exports common type from the root module export
=> add register codec functions

openrewrite/src/javascript/parser.ts, openrewrite/test/javascript/parser/class.test.ts
Add constructor syntax support
=> constructor support

openrewrite/src/javascript/parser.ts, openrewrite/test/javascript/parser/class.test.ts, openrewrite/test/javascript/parser/function.test.ts, openrewrite/test/javascript/parser/interface.test.ts, openrewrite/test/javascript/parser/method.test.ts, openrewrite/test/javascript/parser/qualifiedName.test.ts
add support for generic types in js/ts parser
=> add support for generics where missing

openrewrite/src/javascript/parser.ts, openrewrite/test/javascript/parser/arrow.test.ts, openrewrite/test/javascript/parser/class.test.ts, openrewrite/test/javascript/parser/function.test.ts
Implemented `ClassExpression` via `JS.StatementExpression` as an `ClassDeclaration` wrapper.
Refactored `visitQualifiedName` and generalized `visitTypeReference`
=> Implemented support for ClassExpression

openrewrite/src/javascript/parser.ts, openrewrite/src/javascript/remote/receiver.ts, openrewrite/src/javascript/remote/sender.ts, openrewrite/src/javascript/tree/tree.ts, openrewrite/src/javascript/visitor.ts, openrewrite/test/javascript/parser/function.test.ts, openrewrite/test/javascript/parser/method.test.ts, openrewrite/test/javascript/parser/typeAlias.test.ts, rewrite-javascript-remote/src/main/java/org/openrewrite/javascript/remote/JavaScriptReceiver.java, rewrite-javascript-remote/src/main/java/org/openrewrite/javascript/remote/JavaScriptSender.java, rewrite-javascript/src/main/java/org/openrewrite/javascript/JavaScriptVisitor.java, rewrite-javascript/src/main/java/org/openrewrite/javascript/internal/JavaScriptPrinter.java, rewrite-javascript/src/main/java/org/openrewrite/javascript/tree/JS.java
Implemented `visitTypeAliasDeclaration`
=> Implemented TypeDeclaration

rewrite-javascript/src/main/java/org/openrewrite/javascript/JavaScriptParser.java
As a workaround for the issue we have with the JS process returning the LST for a previously parsed source file, the Java parser frontend now creates a new socket for each source file being parsed.
=> Use new socket for each source file

.github/workflows/ci.yml, .github/workflows/publish.yml, .gitignore, openrewrite/.gitignore, openrewrite/package-lock.json, rewrite-javascript-remote-server/build.gradle.kts, rewrite-javascript-remote-server/src/main/resources/package.json, settings.gradle.kts
this PR adds as a JAR an embedded JS Server required for the Moderne CLI. This eliminates the need to run `npm install` and ensures all required JS dependencies are bundled with the CLI so one can run it behind the firewall.
=> add jar to embed and bundle JS server as a jar

openrewrite/src/javascript/parser.ts, openrewrite/test/javascript/parser/empty.test.ts, openrewrite/test/javascript/parser/flowAnnotation.test.ts
If a source file contains `@flow` annotation, the `FlowSyntaxNotSupportedError` is thrown as a `ParseError`, and the file is skipped from parsing.
Also added code to check syntax errors before parsing
=> Throwing FlowSyntaxNotSupportedError if meets @flow annotation in a source file

openrewrite/src/javascript/parser.ts, openrewrite/src/javascript/parserUtils.ts, openrewrite/test/javascript/e2e/electron-server.files.test.ts, openrewrite/test/javascript/parser/arrow.test.ts, openrewrite/test/javascript/parser/await.test.ts, openrewrite/test/javascript/parser/class.test.ts, openrewrite/test/javascript/parser/decorator.test.ts, openrewrite/test/javascript/parser/enum.test.ts, openrewrite/test/javascript/parser/flowAnnotation.test.ts, openrewrite/test/javascript/parser/for.test.ts, openrewrite/test/javascript/parser/if.test.ts, openrewrite/test/javascript/parser/import.test.ts, openrewrite/test/javascript/parser/importType.test.ts, openrewrite/test/javascript/parser/namespace.test.ts, openrewrite/test/javascript/parser/qualifiedName.test.ts, openrewrite/test/javascript/parser/return.test.ts, openrewrite/test/javascript/parser/while.test.ts, openrewrite/test/javascript/parser/with.test.ts, openrewrite/test/javascript/parser/yield.test.ts
If a source file has syntax errors, the `ParseError` is generated, and the file is skipped from parsing. 
Syntactically, the check is based on the TS compiler function `ts.getPreEmitDiagnostics`. 
There is a list of error codes that can be ignored or added.
=> Throwing SyntaxError if a parsed source file is syntactically incorrect

openrewrite/src/javascript/parser.ts, openrewrite/src/javascript/parserUtils.ts
As a temporary fix, we detect the invalid surrogate pairs literal and throw ParseError.
Later on, it should be reworked to parse and represent invalid surrogate pairs in a safe way.
=> Temporary fix to prevent ingestion failure for invalid surrogate literals

.gitignore, openrewrite/src/javascript/typeMapping.ts, openrewrite/test/javascript/typeMapping.test.ts
- related to https://github.com/moderneinc/rewrite-remote/issues/93
- improves type mapping and adds tests
=> add type mapping tests and improve boolean mapping

rewrite-javascript/src/main/java/org/openrewrite/javascript/cleanup/UseCaseFallThrough.java
Apply newest `getCaseLabel` instead of `getExpression`
@timtebeek
=> Prevent potential Java 21 issue

openrewrite/src/core/execution.ts, openrewrite/src/core/index.ts, openrewrite/src/core/style.ts, openrewrite/src/core/tree.ts, openrewrite/src/javascript/format/blankLines.ts, openrewrite/src/javascript/parser.ts, openrewrite/src/javascript/style.ts, openrewrite/test/javascript/format/blankLines.test.ts, openrewrite/test/javascript/parser/binary.test.ts, openrewrite/test/javascript/parser/literal.test.ts, openrewrite/test/javascript/parser/object.test.ts, openrewrite/test/javascript/parser/variableDeclarations.test.ts, openrewrite/test/javascript/parser/void.test.ts, openrewrite/test/javascript/recipeHarness.ts, openrewrite/test/javascript/testHarness.ts, rewrite-javascript/src/main/java/org/openrewrite/javascript/format/JavaScriptSpaces.java, rewrite-javascript/src/main/java/org/openrewrite/javascript/format/JavaScriptSpacesVisitor.java, rewrite-javascript/src/main/java/org/openrewrite/javascript/style/BlankLinesStyle.java, rewrite-javascript/src/main/java/org/openrewrite/javascript/style/ImportsStyle.java, rewrite-javascript/src/main/java/org/openrewrite/javascript/style/IntelliJ.java, rewrite-javascript/src/main/java/org/openrewrite/javascript/style/JavaScriptStyle.java, rewrite-javascript/src/main/java/org/openrewrite/javascript/style/PunctuationStyle.java, rewrite-javascript/src/main/java/org/openrewrite/javascript/style/SpacesStyle.java, rewrite-javascript/src/main/java/org/openrewrite/javascript/style/TabsAndIndentsStyle.java, rewrite-javascript/src/main/java/org/openrewrite/javascript/style/WrappingAndBraces.java, rewrite-javascript/src/test/java/org/openrewrite/javascript/format/JavaScriptSpacesTest.java
- added styles classes 
- added basic Recipe and Formatter infrastructure
- added BlankLines visitor formatter
=> Formatter infrastructure and BlankLines formatter

rewrite-javascript/src/main/java/org/openrewrite/javascript/JavaScriptVisitor.java
The `JS.ArrowFunction#body` property was visited twice.
=> Fix `JavaScriptVisitor` bug
